## Import Libraries

In [233]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Import Dataset from Seaborn libraries

In [235]:
df = sns.load_dataset('titanic')

In [236]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [237]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [238]:
data = df[['age','sex','fare','class','who','adult_male','alone','survived']].dropna()

In [239]:
data.head()

    age     sex     fare  class    who  adult_male  alone  survived
0  22.0    male   7.2500  Third    man        True  False         0
1  38.0  female  71.2833  First  woman       False  False         1
2  26.0  female   7.9250  Third  woman       False   True         1
3  35.0  female  53.1000  First  woman       False  False         1
4  35.0    male   8.0500  Third    man        True   True         0

## Feature Engineering

In [241]:
data.describe().T

          count       mean        std   min     25%      50%     75%       max
age       714.0  29.699118  14.526497  0.42  20.125  28.0000  38.000   80.0000
fare      714.0  34.694514  52.918930  0.00   8.050  15.7417  33.375  512.3292
survived  714.0   0.406162   0.491460  0.00   0.000   0.0000   1.000    1.0000

In [242]:
data.describe(include = 'O').T

    count unique   top freq
sex   714      2  male  453
who   714      3   man  413

In [243]:
data.isnull().sum()

age           0
sex           0
fare          0
class         0
who           0
adult_male    0
alone         0
survived      0
dtype: int64

### Label Encoding (Converting Categorical column into Numerical column)

In [245]:
data['sex'].unique()

array(['male', 'female'], dtype=object)

In [246]:
data['sex'].value_counts()

sex
male      453
female    261
Name: count, dtype: int64

In [247]:
data['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [248]:
data['who'].value_counts()

who
man      413
woman    218
child     83
Name: count, dtype: int64

In [249]:
data['class'].unique()

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [250]:
data['adult_male'].unique()

array([ True, False])

In [251]:
data['alone'].unique()

array([False,  True])

In [252]:
from sklearn.preprocessing import LabelEncoder

In [253]:
label = LabelEncoder()

In [254]:
data['sex'] = label.fit_transform(data['sex'])

In [255]:
data['who'] = label.fit_transform(data['who'])

In [256]:
data['class'] = label.fit_transform(data['class'])

In [257]:
data['adult_male'] = label.fit_transform(data['adult_male'])

In [258]:
data['alone'] = label.fit_transform(data['alone'])

In [259]:
data.head()

    age  sex     fare  class  who  adult_male  alone  survived
0  22.0    1   7.2500      2    1           1      0         0
1  38.0    0  71.2833      0    2           0      0         1
2  26.0    0   7.9250      2    2           0      1         1
3  35.0    0  53.1000      0    2           0      0         1
4  35.0    1   8.0500      2    1           1      1         0

## Feature Scaling to make the same ranges of the values , so model can learn pattren easily from all values

In [261]:
from sklearn.preprocessing import StandardScaler

In [262]:
scale = StandardScaler()

In [263]:
data['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
885    39.0
886    27.0
887    19.0
889    26.0
890    32.0
Name: age, Length: 714, dtype: float64

In [264]:
data['age'] = scale.fit_transform(data[['age']])

In [265]:
data['fare'] = scale.fit_transform(data[['fare']])

In [266]:
data.head()

        age  sex      fare  class  who  adult_male  alone  survived
0 -0.530377    1 -0.518978      2    1           1      0         0
1  0.571831    0  0.691897      0    2           0      0         1
2 -0.254825    0 -0.506214      2    2           0      1         1
3  0.365167    0  0.348049      0    2           0      0         1
4  0.365167    1 -0.503850      2    1           1      1         0

In [267]:
data['survived'].value_counts()

survived
0    424
1    290
Name: count, dtype: int64

## Train Test Split

In [269]:
from sklearn.model_selection import train_test_split

In [270]:
X = data[['age','sex', 'fare','class','who','adult_male','alone']]
y = data['survived']

In [271]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Balancing Dataset Using SMOTE

In [273]:
!pip install imblearn

Requirement already satisfied: imblearn in d:\ anacona navigator\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in d:\ anacona navigator\lib\site-packages (from imblearn) (0.12.3)
Requirement already satisfied: numpy>=1.17.3 in d:\ anacona navigator\lib\site-packages (from imbalanced-learn->imblearn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in d:\ anacona navigator\lib\site-packages (from imbalanced-learn->imblearn) (1.13.1)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\dell\appdata\roaming\python\python312\site-packages (from imbalanced-learn->imblearn) (1.6.1)
Requirement already satisfied: joblib>=1.1.1 in d:\ anacona navigator\lib\site-packages (from imbalanced-learn->imblearn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from imbalanced-learn->imblearn) (3.5.0)

[notice] A new release of pip is available: 25.0 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [274]:
 from imblearn.over_sampling import SMOTE

In [275]:
sm = SMOTE(random_state=42)

In [276]:
x_train_sm, y_train_sm = sm.fit_resample(X_train, y_train)

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(

In [277]:
from collections import Counter

In [278]:
print("Before SMOTE :", Counter(y_train))
print("After SMOTE :", Counter(y_train_sm))

Before SMOTE : Counter({0: 337, 1: 234})
After SMOTE : Counter({1: 337, 0: 337})

## ANN Model Settings

In [280]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [281]:
model = Sequential()
model.add(Dense(8, input_dim=7,activation = 'relu'))
model.add(Dense(4, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

D:\ Anacona Navigator\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

## Model Compilation

In [328]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(x_train_sm, y_train_sm, epochs= 50 )

Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8219 - loss: 0.4491
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8173 - loss: 0.4554
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8350 - loss: 0.4215
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8350 - loss: 0.3961
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8122 - loss: 0.4468
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8389 - loss: 0.4221
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8237 - loss: 0.4388
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8192 - loss: 0.4510
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8108 - loss: 0.4570
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8365 - loss: 0.4248
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8445 - loss: 0.4191
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8423 - loss: 0.4256
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8305 - loss: 0.4440
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8365 - loss: 0.4302
Epoch 15/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8169 - loss: 0.4736
Epoch 16/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8146 - loss: 0.4344
Epoch 17/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8061 - loss: 0.4589
Epoch 18/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8191 - loss: 0.4454
Epoch 19/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8073 - loss: 0.4562
Epoch 20/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8049 - loss: 0.4562
Epoch 21/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8250 - loss: 0.4466
Epoch 22/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8376 - loss: 0.4124
Epoch 23/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8331 - loss: 0.4122
Epoch 24/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8253 - loss: 0.4191
Epoch 25/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8423 - loss: 0.3897
Epoch 26/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8369 - loss: 0.4347
Epoch 27/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8274 - loss: 0.4371
Epoch 28/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8420 - loss: 0.4014
Epoch 29/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8362 - loss: 0.4195
Epoch 30/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8272 - loss: 0.4380
Epoch 31/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8283 - loss: 0.4433
Epoch 32/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8105 - loss: 0.4431
Epoch 33/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8297 - loss: 0.4196
Epoch 34/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8171 - loss: 0.4421
Epoch 35/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8430 - loss: 0.4033
Epoch 36/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7953 - loss: 0.4585
Epoch 37/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8378 - loss: 0.4116
Epoch 38/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8437 - loss: 0.4065
Epoch 39/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8061 - loss: 0.4535
Epoch 40/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8347 - loss: 0.4248
Epoch 41/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8280 - loss: 0.3987
Epoch 42/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8339 - loss: 0.4227
Epoch 43/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8371 - loss: 0.4023
Epoch 44/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8319 - loss: 0.4299
Epoch 45/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8226 - loss: 0.4335
Epoch 46/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8329 - loss: 0.4219
Epoch 47/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8333 - loss: 0.4289
Epoch 48/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8151 - loss: 0.4305
Epoch 49/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8377 - loss: 0.4100
Epoch 50/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8189 - loss: 0.4413

In [330]:
from sklearn.metrics import accuracy_score

In [332]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Accuracy: 0.7482517482517482